account/urls.py
from django.contrib import admin
from django.urls import path , re_path , include
from . import views

app_name = 'AC'

urlpatterns = [
    # path('login/', views.login , name='login'),
    path("login/" , views.login , name='login'),
    re_path(r'^signup/' , views.signup , name='signup'),
    re_path('^', include('django.contrib.auth.urls')),
    # path("logout/" , views.logout, name='logout'),
]

updown/urls.py
from django.contrib import admin
from django.urls import path , re_path , include
from . import views

app_name = 'UD'

urlpatterns = [
    # re_path(r'^upload/(\d+)', views.upload , name='upload'),
    re_path(r'^upload/(\d+)?', views.upload , name='upload'),
    # re_path(r'^detail/(\d+)?',views.change , name='detail'),
    path('upload/<int:userid>', views.upload , name='upload'),
    re_path(r'^download/', views.download , name='download'),
    re_path(r'^delete/(\d+)?', views.delete,name='delete'),
    re_path(r'^detail/(\d+)?', views.change , name='change'),
    re_path(r"^fail", views.fail , name='fail')
]

window/urls.py
from django.contrib import admin
from django.urls import path , re_path , include
from . import views
from django.conf import settings
from django.conf.urls.static import static
# from ..updown.views import UpdownViews

urlpatterns = [
    re_path(r'^$' ,views.index , name='index'),
    # path('*<userid>' ,views.index , name='index'),
    re_path(r'^about/$' , views.about , name='about'),
    re_path(r'^service/$' ,views.service , name='service'),
    re_path(r"^inquiry/$" , views.inquiry , name='inquiry'),
    re_path(r"^MyFage/(\d+)?" , views.myfage , name='myfage'),

    path('updown/' , include('updown.urls', namespace='UD')),
    path('account/', include('account.urls' , namespace='AC')),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about.html
{% extends 'form.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>

  <style media="screen">

  </style>
</head>
<body>
  <div class="post">
    <h1 class="title">창문마스터의 대해서</h1>
    창문마스터는 거의 5년정도의 경력을 가지고 있는 창문의 대한 모든 정보와 지식을 깨우치시고 지금도
    배우고 계시는 '창문마스터' 입니다.
  </div>

</body>
</html>

{% endblock %}

templates/form.html
{% load static %}
<!-- {% static 'css' as cssDir %} -->
{% static 'image' as imgDir %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <!-- <link rel="stylesheet" href="{% static 'css/style.css' %}?after"> -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script type="text/javascript" src="{% static 'js/go.js' %}"></script>
</head>
<body>
  <script type="text/javascript">
    var home = "{% url 'index' %}";
    var about = "{% url 'about' %}";
    var service = "{% url 'service' %}";
    var inquiry = "{% url 'inquiry' %}";
    var myfage = "{% url 'myfage' user.id %}";

    var logout = "{% url 'AC:logout' %}"
    var login = "{% url 'AC:login' %}";
    var signup = "{% url 'AC:signup' %}";
    var upload = "{% url 'UD:upload' user.id %}";
    var download = "{% url 'UD:download' %}";
    var windowMainBlog = "https://blog.naver.com/dughdhk0802"

    function locationClick(local){
      location.href=local
    }

    var choiseLogout
    // logout할때 재질문
    function checkLogout(choise){
      choiseLogout = confirm("정말 로그아웃하시겠습니까?");
      if(choiseLogout){
        locationClick(logout);
      }else{
        alert("탁월한 선택입니다.");
      }

    }
  </script>


  <div class="wrapper">
    <header class="header">
      <ul>
        <a href="{% url 'index' %}"><img src="{% static 'image/logo.png' %}" alt="img"></a>
        <li onclick='locationClick(home)'><a>Home</a></li>
        <li onclick='locationClick(about)'><a>About</a></li>
        <li onclick='locationClick(service)'><a>Service</a></li>
        <li onclick='locationClick(windowMainBlog)'><a>Inquiry</a></li>
        {% if not user.is_active %}
          <a onclick="locationClick(login)">login</a>
          <a onclick="locationClick(signup)">signup</a>
        {% else %}
          <a onclick="locationClick(logout)" style="cursor: pointer">logout</a>
        {% endif %}
      </ul>
    </header>


      <article class="main">
      {% block content %}
  	  {% endblock %}
      </article>

      <aside class="aside aside-1">
        <div class="aside-left">
          <font><h1>Home</h1></font>
          <ul>
              <li onclick="locationClick(home)"><a>Home</a></li>
              <li onclick="locationClick(about)"><a>About</a></li>
              <li onclick="locationClick(service)"><a>Service</a></li>
              <li onclick="locationClick(inquiry)"><a>Inquiry</a></li>
          <!-- onclick="checkLogout(choiseLogout)" -->
          </ul>
        </div>
      </aside>


      <aside class="aside aside-2">
        <div class="aside-right">
          <font><h1>MyFage</h1></font>
          <ul>
            {% if not user.is_active %} <!-- 회원이 아닐때 -->
              <li onclick="locationClick(login)"><a>Login</a></li>
              <li onclick="locationClick(signup)"><a>Sign Up</a></li>
              <li onclick="locationClick(upload)"><a>UpLoad</a></li>
              <li onclick="locationClick(download)"><a>Download</a></li>
            {% else %} <!-- 회원일떄 -->
              <li onclick="locationClick(myfage)"><a >MyFage</a></li>
              <li onclick="locationClick(logout)"><a>Logout</a></li>
              <li onclick="locationClick(upload)"><a>UpLoad</a></li>
              <li onclick="locationClick(download)"><a>Download</a></li>
            {% endif %}
          <!-- onclick="checkLogout(choiseLogout)" -->
          </ul>
        </div>
      </aside>
    </div> <!-- mainBody ending -->

    <footer class="footer">
        <!-- <ul>
          <li><a href="#">고객센터</a></li>
          <li><a href="#">1대1문의</a></li>
        </ul> -->
      {% block footerContent %}
      {% endblock footerContent %}
    </footer>

</body>
</html>

templates/index.html
{% extends 'form.html' %}
{% load static %}
{% url 'AC:login' as loginUrl %}

{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <link rel="stylesheet" href="{% static 'css/indexStyle.css' %}">
  <script type="text/javascript"></script>
</head>
<style media="screen">
  .post img.postLogo {
    height: 20px;
    float: right;
    cursor: pointer;
    margin: 10px 20px 0 0;
  }
  .popup{
    position:absolute;
    left: 50%;
    top: 50%;
    transform: translate(-50%, -50%);
    width: 500px;
    height: 500px;
    z-index: 5;
    box-shadow: 0 0 10px rgba(0,0,0,0.5);
    background: #fff;
    border-radius: 5px;
    text-align: right;
    padding: 20px;
    box-sizing: border-box;
    opacity: 0;
    transition: all .5s;
  }
  .popup a{color:grey;text-decoration: none;}
  .popup:target{opacity: 1;}
  .popup:target + .dim {opacity: 1; z-index:3;}
  .dim{
    position: absolute;
    left: 0;
    top: 0;
    z-index: -1;
    width:100%;
    height: 100%;
    background: rgba(0,0,0,0.6);
    opacity: 0;
    transition: all .5s;
  }
</style>

<body>
  <script type="text/javascript">
  function checkdelete(location){
    check = confirm("정말 삭제하시겠습니까?" );
    if(check){
      location.href = location;
    }
  }
</script>
  <form action="{% url 'index' %}" method="get">

    {% if not user.is_active %}
    <!-- 회원이 아니라면 -->

    <body onLoad='redirect()'>

    </body>


    {% else %}
    <div class="ContainerUpload">
      <a href='{% url "UD:upload" user.id %}'>
        <img class='uploadLogo' src="{% static 'image/uploadLogoImage.png' %}" alt="img">
        <style media="screen">
          .ContainerUpload .uploadLogo {
            height: 60px;
            margin-bottom: 10px;
          }
        </style>
      </a>
    </div>
    {% endif %}

    {% if user.is_superuser %}
    <!-- 회원이 관리자라면 -->
    <b>{{user.username}}</b> 슈퍼관리자님 환영합니다!<br />
    <hr />

    {% elif user.is_active %}
    <!-- 그냥 회원이라면 -->
    <b>{{user.username}}</b> 님 환영합니다!<br>
    <hr>


    {% endif %}

    {% for posts in post %}

    <!-- #################### POST ############## -->
    <div class="post">
      <!-- USER POST -->
      <a href="#popup"><img class='postLogo' src="{% static 'image/postLogo2.png' %}" alt="img" /></a>
      <div class="post-user">{{ posts.사용자 }} - {{ posts.postdate }}
      </div> <br />

      <!-- IMAGE PSOT -->
      <!-- https://ssungkang.tistory.com/entry/DjangoDate%EC%99%80-Time%EC%9D%84-%EB%82%98%ED%83%80%EB%82%B4%EB%8A%94-template-filter -->
      <div class="post-image">
        <a><img src="{{ posts.사진.url }}" alt="img" width="100%"></a>
      </div><br />

      <!-- CONTENT POST -->
      <div class="post-content">
        <span style="font-weight: bold;">{{ posts.사용자 }}</span> {{ posts.content }}
      </div><br />

      <!-- FOOTER POST -->
      <hr style="border-color: #fafafa;" />


      <div class="post-footer">


      </div>
    </div>
    {% endfor %}
    <!-- <div class="popup" id="popup">
      <a href="">닫기</a>
      수정
      <a href="{% url 'UD:change' %}"></a>
      <input type="button" name='change' value="수정">

      삭제
      <a href="{% url 'UD:delete' photo.id %}">
        <input type="button" name="delete" value="삭제">
      </a>
    </div>
    <div class="dim"></div> -->
  </form>

</body>

</html>
{% endblock content %}

{% if user.is_active %}
{% block footerContent %}
<div class="ContainerUpload" align='center'>
  <h4><a href="{% url 'UD:upload' user.id %}">UpLoad</a></h4>
</div>
{% endblock footerContent %}
{% endif %}

templates/inquiry.html
{% extends 'form.html' %}
{% block content %}



<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <h1>inquiry page</h1>

</body>
</html>
{% endblock %}

templates/myfage.html
{% extends 'form.html' %}
{% load static %}
{% block content %}


<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static 'css/indexStyle.css' %}">
  <title>Document</title>
</head>
<body>
  <div id='main' align='center'>
    <br>
    userID : {{user.id}} <br />
    아이디 : {{user.username}} <br>
    비밀번호 : {{user.password}} <br>
    이메일 : {{user.email}} <br>
    로그인 여부 : {{user.is_active}} <br>
    관리자 여부 : {{user.is_staff}} <br>
    최고관리자 여부 : {{user.is_superuser}} <br>
    최종접속시간 : {{user.last_login}} <br>

  </div>


  <form action="{% url 'myfage' %}" method="get">

    {% for posts in post %}
    <div class="post">
      <!-- USER POST -->
      <div class="post-user">{{ posts.사용자 }} - {{ posts.postdate }}
                                            <!-- <img class='postLogo' src="{% static 'image/postLogo.png' %}" alt="img"> -->
      </div> <br />

      <!-- IMAGE PSOT -->                                      <!-- https://ssungkang.tistory.com/entry/DjangoDate%EC%99%80-Time%EC%9D%84-%EB%82%98%ED%83%80%EB%82%B4%EB%8A%94-template-filter -->
      <div class="post-image">
        <a><img src="{{ posts.사진.url }}" alt="img" width="100%"></a>
      </div><br />

      <!-- CONTENT POST -->
      <div class="post-content">
        {{ posts.content }}
      </div><br />

      <!-- FOOTER POST -->
      <hr />
      <div class="post-footer">


        <!-- {% if user.username  %} -->
        <!-- 수정 -->
        <a href="{% url 'UD:change' posts.id %}">
          <input type="button" name='change' value="수정">
        </a>

        <!-- 삭제 -->
        <!-- <script type="text/javascript">
          var location = "{% url 'UD:delete' posts.id %}"
        </script> -->
        <!-- <a onclick=checkdelete(location)> -->
        <a href="{% url 'UD:delete' posts.id %}">
          <input type="button" name="delete" value="삭제">
        </a>
        <!-- {% endif %} -->

      </div>
    </div>
    {% endfor %}

  </form>
</body>
</html>

{% endblock content %}

templates/service.html
{% extends 'form.html' %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <style media="screen">
    .main-title{
      position: relative;
      top: -9px;
    }
  </style>
</head>
<body>
  <h1 class="main-title">'저희가 하는 일'</h1>
  <hr>
  <div class="post POST1">
    <h2 class="title">1번째 외풍차단</h2>
    <div class="content">
      바람의 통로를 차단하여서 온도를 낮추어줍니다.
    </div>
  </div>
  <div class="post POST2">
    <h2 class="title">2번째 벌레차단</h2>
    <div class="content">
      많은 벌레 각벌레들의 모든경로를 차단하여서 벌레를 차단합니다.
    </div>
  </div>

</body>
</html>

{% endblock %}